apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jerney-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/yamazalaharsha/Jerney-devsecops.git'
    targetRevision: devsecops # The branch ArgoCD will watch
    path: K8s # The folder containing your Kubernetes manifests
  destination:
    server: 'https://kubernetes.default.svc' # This means the local cluster where ArgoCD is running
    namespace: jerney # The namespace to deploy the application into
  syncPolicy:
    automated:
      prune: true # Automatically delete resources that are removed from Git
      selfHeal: true # Automatically revert any manual changes made in the cluster
    syncOptions:
    - CreateNamespace=true # Automatically create the 'jerney' namespace if it doesn't exist
