FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci && npm cache clean --force

# stage 2: Production stage

FROM node:20-alpine AS production

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

RUN apk add --no-cache dumb-init

WORKDIR /app

COPY --from=build /app/node_modules ./node_modules
COPY src/ ./src

USER appuser

EXPOSE 5000

ENTRYPOINT [ "dumb-init", "--" ]

CMD ["node", "src/index.js"]
